# Generated by Django 5.2.7 on 2025-10-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pedido_datapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
