# Generated by Django 5.2.7 on 2025-10-21 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pedido_datapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='dataServico',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
