# Generated by Django 5.2.7 on 2025-10-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_servico_dataservico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='dataServico',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='idPet',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='idVeterinario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='anexos',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idPet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pet'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idVeterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.veterinario'),
        ),
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anexos',
            name='idServico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.servico'),
        ),
    ]
