# Generated by Django 5.2.7 on 2025-10-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_servico_anexo_remove_servico_dataservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='imagemPet',
            field=models.ImageField(blank=True, null=True, upload_to='imagemPet'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
